field: 4371dbc4-e7d1-4f29-98aa-7b42a8a53585 # Service Content
fieldLayouts:
  a1979822-6413-4b44-ba55-b694aa9fd0b2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 53877b4f-7e25-425b-bdd0-d3269a768c06 # Prayer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c410fcf-d4d9-4072-850b-81e28806a200
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 09c709c3-7712-4e3e-8415-fb62235a559b
        userCondition: null
fields:
  53877b4f-7e25-425b-bdd0-d3269a768c06: # Prayer
    columnSuffix: bnsqdohh
    contentColumnType: boolean
    fieldGroup: null
    handle: prayer
    instructions: 'Allow people to request private chat with Hosts via the Request Prayer button.'
    name: Prayer
    searchable: false
    settings:
      default: true
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: prayer
name: Prayer
sortOrder: 3
