field: 4371dbc4-e7d1-4f29-98aa-7b42a8a53585 # Service Content
fieldLayouts:
  e9f09b3f-2fe4-4664-b48f-7a149575f873:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dec75073-e032-4fd0-9c5b-acd024d1a19c # Public Chat
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3fb5e16b-ffcb-4cd3-9356-da2ea73e1d8d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2c663d27-e9cc-4aaa-8e17-ebf6b50b062f # Chat Duration
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c26752c7-4e4b-4a66-bbc4-35843638b3b6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 13b0f6e7-66e4-4109-8687-d51db1559dc9
        userCondition: null
fields:
  2c663d27-e9cc-4aaa-8e17-ebf6b50b062f: # Chat Duration
    columnSuffix: lyhxqqpa
    contentColumnType: integer(10)
    fieldGroup: null
    handle: chatDuration
    instructions: 'Allow people to chat {{ entry.chatDuration }} minutes before the Service begins.'
    name: 'Chat Duration'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  dec75073-e032-4fd0-9c5b-acd024d1a19c: # Public Chat
    columnSuffix: mtcxmxke
    contentColumnType: boolean
    fieldGroup: null
    handle: publicChat
    instructions: null
    name: 'Public Chat'
    searchable: false
    settings:
      default: true
      offLabel: 'Off'
      onLabel: 'On'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: publicChat
name: 'Public Chat'
sortOrder: 2
