field: 4371dbc4-e7d1-4f29-98aa-7b42a8a53585 # Service Content
fieldLayouts:
  865b544a-da0b-43af-a178-a606828ff754:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ba928432-081a-40a5-b0b8-a62dbb202a37 # Video Source
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4d890b32-1565-46ec-96ed-415c30888ce2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ff1b161f-288b-415b-8247-bc965004da15
        userCondition: null
fields:
  ba928432-081a-40a5-b0b8-a62dbb202a37: # Video Source
    columnSuffix: sidukgyh
    contentColumnType: text
    fieldGroup: null
    handle: videoSource
    instructions: "You will need to use an external provider as a video source for each Service.\r\n\r\nYou can use a streaming provider to broadcast a live church Service or a video hosting platform to simulate a live experience for your guests."
    name: 'Video Source'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: true
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: video
name: Video
sortOrder: 4
