fieldLayouts:
  f4c54136-2625-4064-bcfd-5d864e6afa38:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f65cce4f-7dfe-4fdd-a614-a04ac9e7f0c8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0ab48b00-c1f4-4bc3-a412-7139742d84c3 # Feature Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18baeaf8-1ba7-4e85-be68-a5258661242b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ed41f9d9-5586-4584-bfae-d16ac6814cc5 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c0f0fd9-8529-42a3-9585-57e247a2eb35
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 28bc7694-44ee-48bd-8a0d-e6e08145e87d
        userCondition: null
handle: about
hasTitleField: true
name: About
section: 3c348ca9-11eb-457e-baa5-546b3554b5fd # About
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
