fieldLayouts:
  0ec78957-21f5-409e-8839-6175a75f780b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 717bcda9-3fb6-4747-b3b9-62fe0fae3193
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ed41f9d9-5586-4584-bfae-d16ac6814cc5 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43139a72-d94d-4db2-8919-e0d0aa802924
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 48a53807-48e0-437f-83ca-8fa2b2314716
        userCondition: null
handle: homepage
hasTitleField: true
name: Home
section: ac08a449-35cb-47be-b792-75d1de829c9b # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
