fieldLayouts:
  e743bd47-ebfb-458f-b9ef-e87593a3b599:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e44c216d-3f1d-4693-9dd0-1ae968d7c37f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 762e7b93-b622-4dd3-a5a4-3de3d6bc5b76 # breadcrumbs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ddf07394-667b-4ad4-bc17-46faa7a5e55f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0ab48b00-c1f4-4bc3-a412-7139742d84c3 # Feature Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab4485c3-80ba-42c3-acfb-300211906504
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ed41f9d9-5586-4584-bfae-d16ac6814cc5 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8ed8b86-0f82-4d00-9e5c-e80c08ffe065
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fe71f3d9-6f5d-48ae-8a7b-9c8b363ec99f
        userCondition: null
handle: news
hasTitleField: true
name: News
section: 3f78ef20-a912-4935-970a-6e41405dc2cd # News
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
