fieldLayouts:
  f0568f46-aef6-439d-8e1c-788e409ef835:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a9886f2c-b9e9-4abb-94ed-6b9da71122cc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4c5db8b4-cb62-4005-b223-640e932ef612 # Next Time
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ad5b6a9-b459-4146-8f40-a7385a55676b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 739aa8d8-3d03-448d-a64e-c3c96bfddccd # Next Day
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1bf31119-f762-4f1f-9a52-cc4b4ee04033
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 021dbe12-f2c4-40df-a709-4647865b63b2 # Year
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80f9fa7e-fc21-44de-aee5-2ebf24cd8ebc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 012a28a1-7ce0-4e0b-a86e-d87e61cc107a # Month
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4588b99-41eb-4061-a8c5-2b8ebcd4c9d4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6be54ded-2b15-44bd-9fb0-4a190b2ffae9 # Day
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9286495d-ea53-4934-bd5b-e58ccbff30bb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c9fbc9e2-90fe-4e01-8ae8-0b517fd35ce1 # Start Hour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3f8a6e1-2a37-41d7-ac21-738a6b347c00
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 618ffb7e-bb61-43ed-87e7-1d42bdb05be9 # Start Minute
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 864e8b95-2016-4311-8d1c-6b881031dd89
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c2478540-8562-4206-8886-4e2ce8fe2dac # End Day
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40c7fe36-e10c-4368-86ad-f5080749af19
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 99df751f-04ad-486f-bdc9-5ac455f1e0eb # End Hour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec84e49d-c463-476d-be41-5e14d3dd56b6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 339a2932-fced-4019-a378-93ae0aef4cfa # End Minute
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ab66953-7675-40f1-9558-c3eb99862a15
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c47dce25-4136-4fdd-b452-c935b5c29957
        userCondition: null
handle: nextServiceTime
hasTitleField: false
name: 'Next Service Time'
section: a8422304-fb14-41f0-9b22-aa63d76a92da # Next Service Time
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
