allowRepeatingEvents: true
color: '#2CC9F9'
description: 'The default calendar'
descriptionFieldHandle: null
fieldLayout: null
handle: default
hasTitleField: true
icsHash: null
icsTimezone: floating
locationFieldHandle: null
name: Default
siteSettings:
  75796cb4-2c62-434b-9e32-02039069ad59:
    enabledByDefault: true
    hasUrls: null
    siteId: 273f2ad6-554b-4cbd-b78b-eb91e54a84ff # Generic Church
    template: null
    uriFormat: null
titleFormat: null
titleLabel: Title
