fieldLayouts:
  2d9e049e-420b-4155-8e35-bd49a737bf5e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 993accec-9ded-4b8f-abb9-01ef4d3d124b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 10cdb38c-7381-428a-b57d-efeef74a2d93
        userCondition: null
fs: featureImage
handle: featureImage
name: 'Feature Image'
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
