fieldLayouts:
  fc70a1bb-7cb1-4b1e-9875-44eb1e66e2e2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 0fb2cc83-e9d5-43ee-99d4-cc8825afa9df
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b184c65f-1cb4-47f2-9220-7a4e964a4064
        userCondition: null
fs: logo
handle: logo
name: Logo
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
