columnSuffix: rgfstprc
contentColumnType: text
fieldGroup: 3499579d-5255-452e-a33f-03d049a828f5 # Common
handle: description
instructions: null
name: Description
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
