columnSuffix: gavgcdum
contentColumnType: integer(10)
fieldGroup: fb84ade9-aafa-4175-b787-48f864691350 # api
handle: endDay
instructions: null
name: 'End Day'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
