columnSuffix: null
contentColumnType: string
fieldGroup: 3499579d-5255-452e-a33f-03d049a828f5 # Common
handle: featureImage
instructions: null
name: 'Feature Image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: true
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:c35d1838-377a-45df-886c-69ac4e514ec0' # Logo
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: true
  restrictedDefaultUploadSubpath: '{slug}'
  restrictedLocationSource: 'volume:bba60dc0-a15b-4044-a612-53234486cd81' # Feature Image
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources:
    - 'volume:bba60dc0-a15b-4044-a612-53234486cd81' # Feature Image
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
