columnSuffix: zppvmovs
contentColumnType: datetime
fieldGroup: 3499579d-5255-452e-a33f-03d049a828f5 # Common
handle: next_timestamp
instructions: null
name: 'Next Timestamp'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: true
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
