columnSuffix: mzgjaixy
contentColumnType: text
fieldGroup: 3499579d-5255-452e-a33f-03d049a828f5 # Common
handle: schedule
instructions: null
name: Schedule
searchable: false
settings:
  slots:
    __assoc__:
      -
        - open
        -
          __assoc__:
            -
              - name
              - 'Opening Time'
            -
              - handle
              - open
      -
        - close
        -
          __assoc__:
            -
              - name
              - 'Closing Time'
            -
              - handle
              - close
translationKeyFormat: null
translationMethod: none
type: craft\storehours\Field
