columnSuffix: null
contentColumnType: string
fieldGroup: 164551b5-b3a5-4d4f-b3d9-0e2efc5af78b # Services
handle: serviceContent
instructions: null
name: 'Service Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_servicecontent}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
