currLabel: 'Feed Me'
customIcon: null
enabled: true
handle: feed-me
icon: 'E:\Bitnami\wampstack\apache2\vhosts\htdocs_craft4\vendor\craftcms\feed-me\src\icon-mask.svg'
layout: 1cb73877-292a-47d7-86bf-c9c99ea33685 # Default
level: 1
newWindow: false
parent: null
prevLabel: 'Feed Me'
prevLevel: 1
prevParent: null
prevUrl: feed-me
sortOrder: 13
subnavBehaviour: null
type: plugin
url: feed-me
