currLabel: Calendar
customIcon: null
enabled: true
handle: calendar
icon: 'E:\Bitnami\wampstack\apache2\vhosts\htdocs_craft4\vendor\solspace\craft-calendar\packages\plugin\src\icon-mask.svg'
layout: 1cb73877-292a-47d7-86bf-c9c99ea33685 # Default
level: 1
newWindow: false
parent: null
prevLabel: Calendar
prevLevel: 1
prevParent: null
prevUrl: calendar
sortOrder: 5
subnavBehaviour: null
type: plugin
url: calendar
