currLabel: Commerce
customIcon: null
enabled: true
handle: commerce
icon: 'E:\Bitnami\wampstack\apache2\vhosts\htdocs_craft4\vendor\craftcms\commerce\src\icon-mask.svg'
layout: 1cb73877-292a-47d7-86bf-c9c99ea33685 # Default
level: 1
newWindow: false
parent: null
prevLabel: Commerce
prevLevel: 1
prevParent: null
prevUrl: commerce
sortOrder: 37
subnavBehaviour: null
type: plugin
url: commerce
