currLabel: 'Cache Flag'
customIcon: null
enabled: true
handle: cache-flag
icon: 'E:\Bitnami\wampstack\apache2\vhosts\htdocs_craft4\vendor\mmikkel\cache-flag\src\icon-mask.svg'
layout: 1cb73877-292a-47d7-86bf-c9c99ea33685 # Default
level: 1
newWindow: false
parent: null
prevLabel: 'Cache Flag'
prevLevel: 1
prevParent: null
prevUrl: cache-flag
sortOrder: 36
subnavBehaviour: null
type: plugin
url: cache-flag
