currLabel: Entries
customIcon: null
enabled: true
handle: entries
icon: section
layout: 1cb73877-292a-47d7-86bf-c9c99ea33685 # Default
level: 1
newWindow: false
parent: null
prevLabel: Entries
prevLevel: 1
prevParent: null
prevUrl: entries
sortOrder: 2
subnavBehaviour: null
type: craft
url: entries
