currLabel: GraphQL
customIcon: null
enabled: true
handle: graphql
icon: '@appicons/graphql.svg'
layout: 1cb73877-292a-47d7-86bf-c9c99ea33685 # Default
level: 1
newWindow: false
parent: null
prevLabel: GraphQL
prevLevel: 1
prevParent: null
prevUrl: graphql
sortOrder: 23
subnavBehaviour: null
type: craft
url: graphql
