currLabel: Guide
customIcon: null
enabled: true
handle: guide
icon: 'E:\Bitnami\wampstack\apache2\vhosts\htdocs_craft4\vendor\wbrowar\guide\src\icon-mask.svg'
layout: 1cb73877-292a-47d7-86bf-c9c99ea33685 # Default
level: 1
newWindow: false
parent: null
prevLabel: Guide
prevLevel: 1
prevParent: null
prevUrl: guide
sortOrder: 14
subnavBehaviour: null
type: plugin
url: guide
