currLabel: Navigation
customIcon: null
enabled: true
handle: navigation
icon: 'E:\Bitnami\wampstack\apache2\vhosts\htdocs_craft4\vendor\verbb\navigation\src\icon-mask.svg'
layout: 1cb73877-292a-47d7-86bf-c9c99ea33685 # Default
level: 1
newWindow: false
parent: null
prevLabel: Navigation
prevLevel: 1
prevParent: null
prevUrl: navigation
sortOrder: 17
subnavBehaviour: null
type: plugin
url: navigation
