currLabel: Organizer
customIcon: null
enabled: true
handle: organizer
icon: null
layout: 1cb73877-292a-47d7-86bf-c9c99ea33685 # Default
level: 2
newWindow: false
parent: 7ecb3796-87da-4f82-b16e-6753b602c86b
prevLabel: Organizer
prevLevel: 2
prevParent: 7ecb3796-87da-4f82-b16e-6753b602c86b
prevUrl: guide/organizer
sortOrder: 15
subnavBehaviour: null
type: plugin
url: guide/organizer
