currLabel: Schemas
customIcon: null
enabled: true
handle: schemas
icon: null
layout: 1cb73877-292a-47d7-86bf-c9c99ea33685 # Default
level: 2
newWindow: false
parent: 9ac0167f-2537-4e05-bcad-bfbf6dddbd5b
prevLabel: Schemas
prevLevel: 2
prevParent: 9ac0167f-2537-4e05-bcad-bfbf6dddbd5b
prevUrl: graphql/schemas
sortOrder: 24
subnavBehaviour: null
type: craft
url: graphql/schemas
