currLabel: 'System Settings'
customIcon: null
enabled: true
handle: settings
icon: null
layout: 1cb73877-292a-47d7-86bf-c9c99ea33685 # Default
level: 2
newWindow: false
parent: 62da7693-58c8-4d84-9224-236722633b4e
prevLabel: 'System Settings'
prevLevel: 2
prevParent: 62da7693-58c8-4d84-9224-236722633b4e
prevUrl: commerce/settings
sortOrder: 41
subnavBehaviour: null
type: plugin
url: commerce/settings
