currLabel: Settings
customIcon: null
enabled: true
handle: settings
icon: null
layout: 1cb73877-292a-47d7-86bf-c9c99ea33685 # Default
level: 2
newWindow: false
parent: 7ecb3796-87da-4f82-b16e-6753b602c86b
prevLabel: Settings
prevLevel: 2
prevParent: 7ecb3796-87da-4f82-b16e-6753b602c86b
prevUrl: guide/settings/general
sortOrder: 16
subnavBehaviour: null
type: plugin
url: guide/settings/general
