currLabel: Sprig
customIcon: null
enabled: true
handle: sprig
icon: 'E:\Bitnami\wampstack\apache2\vhosts\htdocs_craft4\vendor\putyourlightson\craft-sprig\src\icon-mask.svg'
layout: 1cb73877-292a-47d7-86bf-c9c99ea33685 # Default
level: 1
newWindow: false
parent: null
prevLabel: Sprig
prevLevel: 1
prevParent: null
prevUrl: sprig
sortOrder: 19
subnavBehaviour: null
type: plugin
url: sprig
