currLabel: Tokens
customIcon: null
enabled: true
handle: tokens
icon: null
layout: 1cb73877-292a-47d7-86bf-c9c99ea33685 # Default
level: 2
newWindow: false
parent: 9ac0167f-2537-4e05-bcad-bfbf6dddbd5b
prevLabel: Tokens
prevLevel: 2
prevParent: 9ac0167f-2537-4e05-bcad-bfbf6dddbd5b
prevUrl: graphql/tokens
sortOrder: 25
subnavBehaviour: null
type: craft
url: graphql/tokens
