currLabel: Users
customIcon: null
enabled: true
handle: users
icon: users
layout: 1cb73877-292a-47d7-86bf-c9c99ea33685 # Default
level: 1
newWindow: false
parent: null
prevLabel: Users
prevLevel: 1
prevParent: null
prevUrl: users
sortOrder: 4
subnavBehaviour: null
type: craft
url: users
