currLabel: Utilities
customIcon: null
enabled: true
handle: utilities
icon: tool
layout: 1cb73877-292a-47d7-86bf-c9c99ea33685 # Default
level: 1
newWindow: false
parent: null
prevLabel: Utilities
prevLevel: 1
prevParent: null
prevUrl: utilities
sortOrder: 27
subnavBehaviour: null
type: craft
url: utilities
