currLabel: 'Youtube Live Embed'
customIcon: null
enabled: true
handle: youtubeLiveEmbed
icon: play
layout: 1cb73877-292a-47d7-86bf-c9c99ea33685 # Default
level: 1
newWindow: false
parent: null
prevLabel: 'Youtube Live Embed'
prevLevel: null
prevParent: null
prevUrl: /admin/settings/plugins/youtubeliveembed
sortOrder: 1
subnavBehaviour: null
type: manual
url: /admin/settings/plugins/youtubeliveembed
