defaultPlacement: end
enableVersioning: true
handle: homepage
name: Home
propagationMethod: all
siteSettings:
  273f2ad6-554b-4cbd-b78b-eb91e54a84ff: # Generic Church
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
