defaultPlacement: end
enableVersioning: true
handle: live
name: live
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  273f2ad6-554b-4cbd-b78b-eb91e54a84ff: # Generic Church
    enabledByDefault: true
    hasUrls: true
    template: live/index
    uriFormat: live
type: single
