defaultPlacement: end
enableVersioning: true
handle: nextServiceTime
name: 'Next Service Time'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  273f2ad6-554b-4cbd-b78b-eb91e54a84ff: # Generic Church
    enabledByDefault: true
    hasUrls: true
    template: api\next-service-time.twig
    uriFormat: api/next-service-time
type: single
