tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        disabled: false
        elementCondition: null
        id: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: 0f2f7f2b-a942-4d74-8da2-79c479a0f090
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: d95b6b9e-fb4b-4215-9cf2-6f8b73f4ad85
        userCondition: null
        warning: null
      -
        attribute: countryCode
        elementCondition: null
        id: null
        instructions: null
        label: null
        orientation: null
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: 534d5a79-2d89-4859-900a-64faa4bd8b2c
        userCondition: null
        warning: null
        width: 100
    name: Content
    uid: 15eb2fee-7b00-46f3-a219-648073d54374
    userCondition: null
